"""initial_schema

Revision ID: 9d0b4e071195
Revises: 
Create Date: 2026-06-28 22:02:06.676788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d0b4e071195'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clear old data that is incompatible with the restructured schema.
    # bookings must be cleared before movies (FK dependency).
    op.execute("TRUNCATE TABLE bookings CASCADE")
    op.execute("TRUNCATE TABLE movies CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theatres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theatres_city'), 'theatres', ['city'], unique=False)
    op.create_index(op.f('ix_theatres_id'), 'theatres', ['id'], unique=False)
    op.create_table('screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theatre_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screens_id'), 'screens', ['id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.Enum('REGULAR', 'PREMIUM', 'RECLINER', name='seattype'), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_id', 'row', 'number', name='uq_seat_in_screen')
    )
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_id'), 'shows', ['id'], unique=False)
    op.create_index(op.f('ix_shows_start_time'), 'shows', ['start_time'], unique=False)
    op.create_table('show_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', name='showseatstatus'), nullable=False),
    sa.Column('held_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'seat_id', name='uq_seat_per_show')
    )
    op.create_index(op.f('ix_show_seats_id'), 'show_seats', ['id'], unique=False)
    op.create_index(op.f('ix_show_seats_status'), 'show_seats', ['status'], unique=False)
    op.create_table('booking_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('show_seat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['show_seat_id'], ['show_seats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_seats_id'), 'booking_seats', ['id'], unique=False)
    op.add_column('bookings', sa.Column('show_id', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_constraint(op.f('bookings_movie_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'shows', ['show_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bookings', 'movie_id')
    op.drop_column('bookings', 'seats_booked')
    op.add_column('movies', sa.Column('duration_mins', sa.Integer(), nullable=False))
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('movies', 'show_time')
    op.drop_column('movies', 'available_seats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('available_seats', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('show_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('movies', 'duration_mins')
    op.add_column('bookings', sa.Column('seats_booked', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_movie_id_fkey'), 'bookings', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bookings', 'total_amount')
    op.drop_column('bookings', 'show_id')
    op.drop_index(op.f('ix_booking_seats_id'), table_name='booking_seats')
    op.drop_table('booking_seats')
    op.drop_index(op.f('ix_show_seats_status'), table_name='show_seats')
    op.drop_index(op.f('ix_show_seats_id'), table_name='show_seats')
    op.drop_table('show_seats')
    op.drop_index(op.f('ix_shows_start_time'), table_name='shows')
    op.drop_index(op.f('ix_shows_id'), table_name='shows')
    op.drop_table('shows')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_screens_id'), table_name='screens')
    op.drop_table('screens')
    op.drop_index(op.f('ix_theatres_id'), table_name='theatres')
    op.drop_index(op.f('ix_theatres_city'), table_name='theatres')
    op.drop_table('theatres')
    # ### end Alembic commands ###
